### PR TITLE
Powr 112

### PR DESCRIPTION
**Pull request by RichardDavies**
Adds and enables redirect module.

### CODE REVIEW

**Comment by RichardDavies** [comment]
Out of curiosity, I'd like to know how you resolve the merge conflict in composer.lock file. I assume the hash changes when the dependencies change... how do you determine which hash to keep?

**Comment by joshuami** [comment]
@RichardDavies, that is a great question. I've gone with the content hash from your commit. That is the first time I've seen the conflict when adding a module, so I'll be able to tell you in a moment if I made the correct choice. Research seems to indicate that it should change, but not why it would be a merge conflict rather than just a change.

**Comment by RichardDavies** [comment]
@joshuami I was wondering too why the new hash wasn't just a change. I think it's probably because after I created this branch, it looks like you merged another branch into master containing the new EVA module. So now it doesn't know whether to keep the hash from the EVA module or from my branch.

**Comment by joshuami** [comment]
Well, the good news is that it liked your hash just fine. So we are good to go. I'm going to accept the ticket now and merge our changes to test.

**Pull request merged**
